pkgCache::DepIterator::AllTargets(): don't check a local buffer address for NULL
This fixes the compiler warnings like this:

pkgcache.cc: In member function 'pkgCache::Version** pkgCache::DepIterator::AllTargets()':
pkgcache.cc:400:18: error: the address of 'Res' will never be NULL [-Werror=address]
  400 |          if (Res != 0 && Size > 0) {
      |              ~~~~^~~~
pkgcache.cc:383:13: note: 'Res' declared here
  383 |    Version *Res[1024];
      |             ^~~

Fixes: 46fa5b45f pkgcache.cc (AllTargets): optimize out CheckDep() calls

Before that ALT-specific commit, Res used to be allocated after Size was
determined on a first pass. (Res != 0) was used to tell whether it was the
first or the second pass. That commit made Res just a fixed-size local
buffer and eliminated the need for two passes.

Checking for (Size > 0) is also not really needed, because if (Size ==
0), then the following loop is just a no-op.

(TODO: of course, using a fixed-size buffer is not quite
safe. Therefore, you see an "assert" here. The container could be
perhaps changed to std::vector or std::set. Additionally, std::set or
std::unordered_set would simplify checking for uniqueness, but would
break the traditional order of the returned result and could break
the traditional results of APT's problem resolution.

The uniqueness property was introduced in an ALT-specific commit, preceding
the mentioned one:

3417b3b65 pkgcache.cc (AllTargets): return unique list

)